
version: "3.4"
networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  exec:
    image: koromerzhin/nodejs:15.1.0
    volumes:
      - ${PWD}/app:/app
    command: sh -c "npm install"
    deploy:
      restart_policy:
        condition: none
      labels:
        - "traefik.enable=false"
  www:
    image: koromerzhin/nodejs:15.1.0
    volumes:
      - ${PWD}/app:/app
    networks:
      - proxynetwork
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.socketio.rule=HostRegexp(`socketio.traefik.me`, `socketio.{ip:.*}.traefik.me`)"
        - "traefik.http.routers.socketio-tls.tls.domains[0].main=socketio.traefik.me"
        - "traefik.http.routers.socketio-tls.tls.domains[0].sans=socketio-*.traefik.me"
        - "traefik.http.services.socketio.loadbalancer.server.port=80"